CREATE TABLE IF NOT EXISTS User (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT UNIQUE,
    Email TEXT UNIQUE,
    Password TEXT,
    ProfilePicture TEXT
);

CREATE TABLE IF NOT EXISTS Picture (
    PictureID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER,
    ImagePath TEXT,
    UploadDate DATETIME,
    FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE IF NOT EXISTS Vote (
    VoteID INTEGER PRIMARY KEY AUTOINCREMENT,
    PictureID INTEGER,
    UserID INTEGER,
    Type TEXT CHECK (Type IN ('like', 'dislike')),
    FOREIGN KEY (PictureID) REFERENCES Picture(PictureID),
    FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE IF NOT EXISTS Comment (
    CommentID INTEGER PRIMARY KEY AUTOINCREMENT,
    PictureID INTEGER,
    UserID INTEGER,
    Txt TEXT,
    CommentDate DATETIME,
    FOREIGN KEY (PictureID) REFERENCES Picture(PictureID),
    FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE IF NOT EXISTS Follow (
    FollowID INTEGER PRIMARY KEY AUTOINCREMENT,
    FollowerID INTEGER,
    FolloweeID INTEGER,
    FOREIGN KEY (FollowerID) REFERENCES User(UserID),
    FOREIGN KEY (FolloweeID) REFERENCES User(UserID)
);
