CREATE TABLE IF NOT EXISTS Users (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT UNIQUE,
    Email TEXT UNIQUE,
    Password TEXT,
    ProfilePicture TEXT
);

CREATE TABLE IF NOT EXISTS Images (
    ImageID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER,
    ImagePath TEXT,
    UploadDate DATETIME,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Votes (
    VoteID INTEGER PRIMARY KEY AUTOINCREMENT,
    ImageID INTEGER,
    UserID INTEGER,
    Type TEXT CHECK (Type IN ('like', 'dislike')),
    FOREIGN KEY (ImageID) REFERENCES Images(ImageID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Comments (
    CommentID INTEGER PRIMARY KEY AUTOINCREMENT,
    ImageID INTEGER,
    UserID INTEGER,
    Text TEXT,
    CommentDate DATETIME,
    FOREIGN KEY (ImageID) REFERENCES Images(ImageID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Follows (
    FollowID INTEGER PRIMARY KEY AUTOINCREMENT,
    FollowerID INTEGER,
    FolloweeID INTEGER,
    FOREIGN KEY (FollowerID) REFERENCES Users(UserID),
    FOREIGN KEY (FolloweeID) REFERENCES Users(UserID)
);
